### PR TITLE
Fixed ILanguage implementation. This close #13

### LINKED ISSUE #13: archetypes.multilingual not working in Plone 4.3.4 using Archetypes
translating content within a language root folder results in a site error:

```
    Module plone.app.multilingual.browser.utils, line 155, in current_language_name
  AttributeError: 'NoneType' object has no attribute 'get'
  > /home/frisi/instances/aida/src/plone.app.multilingual/src/plone/app/multilingual/browser/utils.py(155)current_language_name()
      154         lang_info = data.get(lang_code)
  --> 155         return lang_info.get('native', None) or lang_info.get('name')
```
### to reproduce:
1. add german and english as site languages
2. create a folder "about us" in Plone/en
3. in the translations dropdown click "create german"

i was using the following versions, but latest 2.x releases will result in the same error

```
plone.app.multilingual               = git https://github.com/plone/plone.app.multilingual.git branch=2.x
archetypes.multilingual              = git https://github.com/plone/archetypes.multilingual.git branch=2.x
```
### analysis

i started looking into this and fixed the way the current language is computed in `archetypes.multilingual`'s implementation of the `ILanguage` adapter
(see the branch https://github.com/plone/archetypes.multilingual/tree/fix-translation)

now invoking "create german" works and i can save a german version of the document.
however i can't navigate between the translations using the portal-languageselector viewlet
(i did not yet check whether the translation relation is not properly set or if it's the @@multilingual-selector view's fault (this one is new to me coming from LinguaPlone)

looking at the tests of both packages (archetypes.multilingual and p.a.multilingual) it looks like p.a.multilingual is not properly tested or even tested at all for archetypes content types.
there should be a test, similar to test_translate_content.robot but using a layer that configures a plonesite using ATContentTypes instead of plone.app.contenttypes.

am i using the wrong versions here, or will i need to put some effort into getting p.a.multilingual to work with archetypes and dexterity content types for my project?

### PR DESCRIPTION
**Pull request by keul**
The ILanguage implementation for archetypes was totally broken IMO.
Translating contents was not possible.

**Please note** to make things works another change is needed in plone.app.multilingual: https://github.com/plone/plone.app.multilingual/pull/178

Not directly tested but I'm quite sure that also the master/Plone 5 branch is broken in the same way

### CODE REVIEW

**Comment by jensens** [comment]
sorry, rebased with master. need some sleep and fix then

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.
